"""empty message

Revision ID: 301964922c71
Revises: 2fdde8720cfa
Create Date: 2025-07-25 16:49:45.143895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301964922c71'
down_revision = '2fdde8720cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('members_and_courses', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('owners_and_courses', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners_and_courses', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('members_and_courses', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
