"""empty message

Revision ID: c54da6b9598f
Revises: f2baddce4997
Create Date: 2025-07-25 17:01:25.572357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54da6b9598f'
down_revision = 'f2baddce4997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('members_and_courses', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('owners_and_courses', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners_and_courses', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('members_and_courses', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
